### ISSUE TITLE
For Help.

### ISSUE THREAD

**Issue by Gertie123** [sronnqvist/discourse-ablstm#1]
Dear Samuel:
    I downloaded this project, but I can't get the data from the  CoNLL-2016 Shared Task, so I was wondering if I can ask for you help? Could you send me the data? My e-mail is: hahatyt@163.com. Thank you very much.
    Best wishes.
    Tang Yi

**Comment by sronnqvist** [comment]
Dear Tang,

unfortunately, I'm not at liberty to share the data myself. Please
contact the shared task organizers to see if they can provide you access.

Otherwise, you might also be able to obtain it here:
https://catalog.ldc.upenn.edu/LDC2008T05
https://catalog.ldc.upenn.edu/LDC2014T21

Kind regards,
Samuel

**Comment by YRXGC** [comment]
Dear Samuel,

Thanks for your reply, I will try follow your advice. Thank you very much.

Best regards,
Tang Yi

**Comment by Gertie123** [comment]
Dear Samuel,

Thanks for your reply, I will try follow your advice. Thank you very much.

Best regards,
Tang Yi
